/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AnatomyRouteImport } from './routes/anatomy'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CoachingRouteImport } from './routes/coaching'
import { Route as GeneratorRouteImport } from './routes/generator'
import { Route as MotivationRouteImport } from './routes/motivation'
import { Route as TechniqueRouteImport } from './routes/technique'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as ProgramsIndexRouteImport } from './routes/programs.index'
import { Route as ProgramsSlugRouteImport } from './routes/programs.$slug'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AnatomyRoute = AnatomyRouteImport.update({
  id: '/anatomy',
  path: '/anatomy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachingRoute = CoachingRouteImport.update({
  id: '/coaching',
  path: '/coaching',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneratorRoute = GeneratorRouteImport.update({
  id: '/generator',
  path: '/generator',
  getParentRoute: () => rootRouteImport,
} as any)
const MotivationRoute = MotivationRouteImport.update({
  id: '/motivation',
  path: '/motivation',
  getParentRoute: () => rootRouteImport,
} as any)
const TechniqueRoute = TechniqueRouteImport.update({
  id: '/technique',
  path: '/technique',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ProgramsIndexRoute = ProgramsIndexRouteImport.update({
  id: '/programs/',
  path: '/programs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsSlugRoute = ProgramsSlugRouteImport.update({
  id: '/programs/$slug',
  path: '/programs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/shop/$slug',
  path: '/shop/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anatomy': typeof AnatomyRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/coaching': typeof CoachingRoute
  '/generator': typeof GeneratorRoute
  '/motivation': typeof MotivationRoute
  '/technique': typeof TechniqueRoute
  '/chat': typeof AuthenticatedChatRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/programs/': typeof ProgramsIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anatomy': typeof AnatomyRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/coaching': typeof CoachingRoute
  '/generator': typeof GeneratorRoute
  '/motivation': typeof MotivationRoute
  '/technique': typeof TechniqueRoute
  '/chat': typeof AuthenticatedChatRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/programs': typeof ProgramsIndexRoute
  '/shop': typeof ShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/anatomy': typeof AnatomyRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/coaching': typeof CoachingRoute
  '/generator': typeof GeneratorRoute
  '/motivation': typeof MotivationRoute
  '/technique': typeof TechniqueRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/programs/': typeof ProgramsIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anatomy'
    | '/auth'
    | '/cart'
    | '/coaching'
    | '/generator'
    | '/motivation'
    | '/technique'
    | '/chat'
    | '/profile'
    | '/programs/$slug'
    | '/shop/$slug'
    | '/programs/'
    | '/shop/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anatomy'
    | '/auth'
    | '/cart'
    | '/coaching'
    | '/generator'
    | '/motivation'
    | '/technique'
    | '/chat'
    | '/profile'
    | '/programs/$slug'
    | '/shop/$slug'
    | '/programs'
    | '/shop'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/anatomy'
    | '/auth'
    | '/cart'
    | '/coaching'
    | '/generator'
    | '/motivation'
    | '/technique'
    | '/_authenticated/chat'
    | '/_authenticated/profile'
    | '/programs/$slug'
    | '/shop/$slug'
    | '/programs/'
    | '/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AnatomyRoute: typeof AnatomyRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CoachingRoute: typeof CoachingRoute
  GeneratorRoute: typeof GeneratorRoute
  MotivationRoute: typeof MotivationRoute
  TechniqueRoute: typeof TechniqueRoute
  ProgramsSlugRoute: typeof ProgramsSlugRoute
  ShopSlugRoute: typeof ShopSlugRoute
  ProgramsIndexRoute: typeof ProgramsIndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anatomy': {
      id: '/anatomy'
      path: '/anatomy'
      fullPath: '/anatomy'
      preLoaderRoute: typeof AnatomyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaching': {
      id: '/coaching'
      path: '/coaching'
      fullPath: '/coaching'
      preLoaderRoute: typeof CoachingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generator': {
      id: '/generator'
      path: '/generator'
      fullPath: '/generator'
      preLoaderRoute: typeof GeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motivation': {
      id: '/motivation'
      path: '/motivation'
      fullPath: '/motivation'
      preLoaderRoute: typeof MotivationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technique': {
      id: '/technique'
      path: '/technique'
      fullPath: '/technique'
      preLoaderRoute: typeof TechniqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/programs/': {
      id: '/programs/'
      path: '/programs'
      fullPath: '/programs/'
      preLoaderRoute: typeof ProgramsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$slug': {
      id: '/programs/$slug'
      path: '/programs/$slug'
      fullPath: '/programs/$slug'
      preLoaderRoute: typeof ProgramsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/shop/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AnatomyRoute: AnatomyRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CoachingRoute: CoachingRoute,
  GeneratorRoute: GeneratorRoute,
  MotivationRoute: MotivationRoute,
  TechniqueRoute: TechniqueRoute,
  ProgramsSlugRoute: ProgramsSlugRoute,
  ShopSlugRoute: ShopSlugRoute,
  ProgramsIndexRoute: ProgramsIndexRoute,
  ShopIndexRoute: ShopIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
